spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/ticket-realm
          jwk-set-uri: http://keycloak:9090/realms/ticket-realm/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: INFO
    com.example.ticketapp: INFO